name: CI

on: [push]

env:
  DOCKER_REGISTRY: harbor-dev.walhall.io/christoph-test
  IMAGE_NAME: funny-game
  DOCKER_ORG: christoph-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: |
        echo Commit: ${GITHUB_SHA}
        echo Branch: ${GITHUB_REF##*/}
        echo ::set-output name=COMMIT::${GITHUB_SHA}
        echo ::set-output name=BRANCH::${GITHUB_REF##*/}
    - name: Publish image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ env.DOCKER_REGISTRY }}
        tags: "latest,${{ steps.get_version.outputs.COMMIT }}"

    - name: Notify Humanitec
      run: |
        echo "Notifying humanitec about new push for ${DOCKER_REGISTRY}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"
        echo "commit: ${GITHUB_SHA}"
        echo "branch: ${GITHUB_REF##*/}"
        echo "image: ${DOCKER_REGISTRY}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"
        echo "https://dev-api.walhall.io/orgs/${{ env.DOCKER_ORG }}/modules/${{ env.IMAGE_NAME }}/builds"
        curl -s -w "%{http_code}" -H "Content-type: application/json" -d "{\"commit\": \"${GITHUB_SHA}\", \"branch\": \"${GITHUB_REF##*/}\", \"tags\": [],\"image\" : \"${DOCKER_REGISTRY}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}\"}" "https://dev-api.walhall.io/orgs/${{ env.DOCKER_ORG }}/modules/${{ env.IMAGE_NAME }}/builds"
